name: Deploy Next.js FE to LightSail

on:
  push:
    branches:
      - main
    paths:
      - "fe/play-baseball-fe/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./fe/play-baseball-fe
          file: ./fe/play-baseball-fe/Dockerfile
          push: false
          load: true
          tags: play-baseball-fe:latest
          build-args: |
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            NEXT_PUBLIC_NEC=${{ secrets.NEXT_PUBLIC_NEC }}

      - name: Save Docker image
        run: docker save play-baseball-fe:latest > image.tar

      - name: Copy Docker image to LightSail
        env:
          PRIVATE_KEY: ${{ secrets.FE_KEY }}
          HOST: ${{ secrets.FE_HOST }}
          USER: ubuntu
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key image.tar ${USER}@${HOST}:~/image.tar
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
            docker load < image.tar
            docker stop fe-container || true
            docker rm fe-container || true
            docker run -d --name fe-container -p 8080:3000 \
              -e NODE_ENV=production \
              -e NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} \
              -e NEC=${{ secrets.NEXT_PUBLIC_NEC }} \
              play-baseball-fe:latest
          '