name: Deploy play-baseball-fe to LightSail

on:
  push:
    branches:
      - main
    paths:
      - "fe/play-baseball-fe/**"
      - ".github/workflows/FE CD.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t play-baseball-fe:latest \
            --build-arg NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} \
            --build-arg NEXT_PUBLIC_NEC=${{ secrets.NEXT_PUBLIC_NEC }} \
            ./fe/play-baseball-fe

      - name: Save Docker image
        run: docker save play-baseball-fe:latest > image.tar

      - name: Deploy to LightSail
        env:
          PRIVATE_KEY: ${{ secrets.FE_KEY }}
          HOST: ${{ secrets.FE_HOST }}
          USER: ubuntu
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key image.tar ${USER}@${HOST}:~/image.tar
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} << EOF
            docker load < image.tar
            docker stop play-baseball-fe || true
            docker rm play-baseball-fe || true
            docker run -d --name play-baseball-fe -p 3000:3000 play-baseball-fe:latest
          
            echo "Updating Caddyfile..."
            echo "${{ secrets.NEXT_PUBLIC_NEC }} {
              reverse_proxy localhost:3000
            }" | sudo tee /etc/caddy/Caddyfile
          
            echo "Reloading Caddy config..."
            sudo systemctl reload caddy
          
            rm image.tar
          EOF
          rm -f private_key